#!/bin/sh
#set -e     # Abort upon error
#set -u     # Abort upon udefined variable
#set -x     # Print every command
#set -o pipefail # Prevents errors in a pipeline from being masked (not supported by dash yet)

#######################################
#   Description:
#       Install arch
#   Usage:
#       ./install
#   Arguments:
#        None
#   Returns:
#       0 upon success
#       >=1 upon error
#######################################
main() {
    # Check if $USAGE is respected
    readonly USAGE='Usage: ./install'
    [ "$#" = 0 ] || { err "Error: 0 argument(s) expected, $# received"; err "$USAGE"; return 1; }

    # Arguments
    readonly hostname="$(cat /etc/hostname)"
    [ -f "env/$hostname.env" ] || { err "Error: no env file was found for '$hostname'"; return 2; }

    load_env
    user_create
    locale_update
    packages_install
    aur_install
}

#######################################
# Load env
#######################################
load_env() {
    # Load general and specific .env
    set -a; . env/env; set +a
    set -a && . "env/$hostname.env" && set +a
}

#######################################
# Create unprivileged user
#######################################
user_create() {
    useradd -m -G wheel -s /bin/bash "$AI_USER_NAME"
    passwd "$AI_USER_NAME"
}

#######################################
# Updates locales and generate
#######################################
locale_update() {
    hwclock --systohc

    [ ! -z "$AI_SYSTEM_KEYMAP" ] \
        && localectl set-keymap "$AI_SYSTEM_KEYMAP" \
        && localectl set-x11-keymap "$AI_SYSTEM_KEYMAP"

    locale-gen
}


#######################################
# Install packages
#######################################
packages_install() {
    pacman -Syu --needed \
        git vim curl wget dash nano man-pages man-db \
        dnsutils networkmanager networkmanager-openvpn \
        reflector os-prober grub efibootmgr \
        pipewire pipepiwe-alsa pipepiwe-pulse pipepiwe-jack \
        $AI_SYSTEM_PACKAGES_EXTRA

    # Configure sudo
    sed -i 's/#%wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
}

#######################################
# Install pkg from AUR
#######################################
aur_install() {
    readonly tmp="$(mktemp -d)"

    for package in paru-bin dashbinsh $AI_SYSTEM_PACKAGES_AUR_EXTRA; do
        su "$AI_USER_NAME" -c "\
            mkdir '$tmp/$package' \
            && git clone 'https://aur.archlinux.org/$package.git/' \"$tmp/$package\" \
            && cd \"\$_\" \
            && makepkg --noconfirm -s \
            "

        pacman --noconfirm -U "$tmp/$package"/*.pkg.tar.xz
    done

    rm -rf "$tmp"
}

#######################################
#   Print error message to stderr
#   https://google.github.io/styleguide/shellguide.html
#######################################
err() { echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2; }

main "$@"; exit
